'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
type Data={settings:{key:string,value:string}[],submissions:any[],sermons:any[],events:any[]};
const groups=[
 {title:'Service & announcement',description:'Top notice and every weekly service time.',fields:[['announcement_text','Top announcement','Join us this Sunday'],['announcement_link_text','Announcement link','Plan your visit →'],['sunday_times','Sunday service times','8:00 AM & 10:30 AM'],['wednesday_time','Wednesday service time','5:30 PM'],['friday_time','Friday prayer time','6:00 PM']]},
 {title:'Homepage wording',description:'Main welcome message and introduction.',fields:[['hero_welcome','Small welcome heading','Welcome home'],['hero_heading','Main heading','Encounter God.'],['hero_accent','Highlighted heading','Discover purpose.'],['hero_tagline','Homepage tagline','A place to belong. A people becoming like Christ.'],['about_heading','About heading','More than a service.'],['about_accent','About highlighted heading','A family to call home.'],['about_text','About paragraph','We are a growing family of believers committed to knowing Jesus, living His Word and sharing His love with our community.']]},
 {title:'Impact numbers',description:'The four animated statistics and labels.',fields:[['impact_1_number','First number','250'],['impact_1_label','First label','Families reached'],['impact_2_number','Second number','18'],['impact_2_label','Second label','Outreach projects'],['impact_3_number','Third number','12'],['impact_3_label','Third label','Ministry groups'],['impact_4_number','Fourth number','1'],['impact_4_label','Fourth label','Family in Christ']]},
 {title:'Visit section',description:'The first-visit message and button.',fields:[['visit_kicker','Small heading','Your first Sunday'],['visit_heading','Visit heading','We can’t wait to meet you.'],['visit_text','Visit paragraph','Visiting a new church can feel like a big step. We’ll make it simple—from directions and parking to helping your children settle in.'],['visit_button','Visit button text','Let us know you’re coming']]},
 {title:'Leadership',description:'Names and titles shown with the leadership photographs.',fields:[['leader_name','Female ministry leader name','Ministry Leader'],['leader_title','Female ministry leader title','Leader, Bread of Life Divine Covenant Ministry'],['pastor_name','Pastor name','Pastor'],['pastor_title','Pastor title','Pastor, Bread of Life Divine Covenant Ministry']]},
 {title:'Church contact & social media',description:'Address, contact details and every official social page.',fields:[['church_phone','Church phone','+234 800 000 0000'],['church_email','Church email','hello@breadoflifedcm.org'],['church_address','Church address','Your Church Address, Your City, Nigeria'],['youtube_channel','YouTube channel','https://youtube.com/@bread_of_life_dcm'],['instagram_url','Instagram page','https://www.instagram.com/bread_of_life_dcm'],['facebook_url','Facebook page','https://www.facebook.com/profile.php?id=61562933086620'],['tiktok_url','TikTok page','https://vm.tiktok.com/ZS9Smb2A5uNWJ-aSViI/']]}
] as const;
export default function Dashboard({email}:{email:string}){
 const[data,setData]=useState<Data|null>(null),[tab,setTab]=useState('overview');
 const load=useCallback(()=>fetch('/api/admin').then(r=>r.json()).then(setData),[]);
 useEffect(()=>{load()},[load]);
 const saved=useMemo(()=>Object.fromEntries((data?.settings||[]).map(x=>[x.key,x.value])),[data]);
 async function send(payload:any){const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Unable to save');await load()}
 function submit(action:string,e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;send({action,...Object.fromEntries(new FormData(f))});if(action==='sermon'||action==='event')f.reset()}
 function saveGroup(e:FormEvent<HTMLFormElement>){e.preventDefault();send({action:'settings_bulk',values:Object.fromEntries(new FormData(e.currentTarget))})}
 return <div className="admin-shell"><aside><div className="admin-brand"><img src="/logo.png" alt="Church logo"/><span><b>Bread of Life</b><small>Church manager</small></span></div>{['overview','messages','sermons','events','website editor'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<a href="/">← View website</a></aside><section className="admin-main"><header><div><small>Secure administration</small><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1></div><span>{email}</span></header>{!data?<p>Loading church records…</p>:<>
 {tab==='overview'&&<><div className="stats"><article><b>{data.submissions.length}</b><span>Messages</span></article><article><b>{data.submissions.filter(x=>x.status==='new').length}</b><span>New requests</span></article><article><b>{data.sermons.length}</b><span>Sermons</span></article><article><b>{data.events.length}</b><span>Events</span></article></div><div className="panel admin-tip"><h2>Quick website editing</h2><p>Open <b>Website editor</b> to change service times, homepage wording, impact numbers, leadership details, social-media links and the visit section.</p></div></>}
 {tab==='messages'&&<div className="panel"><h2>Prayer, visits & enquiries</h2>{data.submissions.map(x=><article className="record" key={x.id}><div><b>{x.name}</b><small>{x.type} · {x.contact}</small><p>{x.message}</p></div><select value={x.status} onChange={e=>send({action:'status',id:x.id,status:e.target.value})}><option>new</option><option>contacted</option><option>resolved</option></select></article>)}</div>}
 {tab==='sermons'&&<div className="two"><form className="panel" onSubmit={e=>submit('sermon',e)}><h2>Add YouTube message</h2><label>YouTube link or video ID<input name="youtubeId" required/></label><label>Message title<input name="title" required/></label><label>Pastor or speaker<input name="pastor" required/></label><label>Duration<input name="duration" placeholder="42:10" required/></label><label className="check"><input type="checkbox" name="featured"/> Feature on homepage</label><button>Add message</button></form><div className="panel"><h2>Video library</h2>{data.sermons.map(x=><article className="record" key={x.id}><div><b>{x.title}</b><small>{x.pastor} · {x.duration}</small></div><button onClick={()=>send({action:'delete_sermon',id:x.id})}>Delete</button></article>)}</div></div>}
 {tab==='events'&&<div className="two"><form className="panel" onSubmit={e=>submit('event',e)}><h2>Add upcoming event</h2><label>Event name<input name="title" required/></label><label>Date<input name="eventDate" type="date" required/></label><label>Time<input name="eventTime" type="time" required/></label><label>Location<input name="location"/></label><button>Add event</button></form><div className="panel"><h2>Edit upcoming events</h2>{!data.events.length&&<p>No events yet. Add one using the form.</p>}{data.events.map(x=><form className="event-editor" key={x.id} onSubmit={e=>{e.preventDefault();send({action:'edit_event',id:x.id,...Object.fromEntries(new FormData(e.currentTarget))})}}><input name="title" defaultValue={x.title}/><input name="eventDate" type="date" defaultValue={x.event_date}/><input name="eventTime" type="time" defaultValue={x.event_time}/><input name="location" defaultValue={x.location} placeholder="Location"/><div><button>Save event</button><button type="button" className="delete" onClick={()=>send({action:'delete_event',id:x.id})}>Delete</button></div></form>)}</div></div>}
 {tab==='website editor'&&<div className="settings-groups">{groups.map(g=><form className="panel settings-card" key={g.title} onSubmit={saveGroup}><h2>{g.title}</h2><p>{g.description}</p><div className="settings-grid">{g.fields.map(([key,label,fallback])=><label key={key}>{label}{key.endsWith('_text')||key==='about_text'?<textarea name={key} rows={3} defaultValue={saved[key]||fallback}/>:<input name={key} defaultValue={saved[key]||fallback}/>}</label>)}</div><button>Save {g.title}</button></form>)}</div>}
 </>}</section></div>
}
