'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import ContentManager,{ContentItem} from './content-manager';
type Data={settings:{key:string,value:string}[];submissions:any[];sermons:any[];events:any[];contentItems:ContentItem[];admins:string[]};
const PRIMARY_ADMIN='garbajohn101@gmail.com';
const groups=[
 {title:'Service times & announcement',description:'The top banner and all weekly gathering times.',fields:[['announcement_text','Top announcement','Join us this Sunday'],['announcement_link_text','Announcement link text','Plan your visit →'],['sunday_times','Sunday service times','8:00 AM & 10:30 AM'],['wednesday_time','Wednesday service time','5:30 PM'],['friday_time','Friday prayer time','6:00 PM']]},
 {title:'Homepage introduction',description:'The main welcome and “Who we are” wording.',fields:[['hero_welcome','Small hero heading','Welcome home'],['hero_heading','Hero main line','Encounter God.'],['hero_accent','Hero highlighted line','Discover purpose.'],['hero_tagline','Hero tagline','A place to belong. A people becoming like Christ.'],['about_heading','About heading','More than a service.'],['about_accent','About highlighted heading','A family to call home.'],['about_text','About paragraph','We are a growing family of believers committed to knowing Jesus, living His Word and sharing His love with our community.']]},
 {title:'Hero buttons & belonging message',description:'Edit both hero actions and the message beside the three member photographs.',fields:[['hero_primary_text','Primary button text','Plan your visit'],['hero_primary_url','Primary button link','#visit'],['hero_secondary_text','Second button text','Watch a message'],['hero_secondary_url','Second button link','#sermons'],['hero_proof_title','Belonging title','You belong here'],['hero_proof_text','Belonging description','Join a growing family of faith'],['prayer_button_text','Floating prayer button','Prayer request']]},
 {title:'Quick information cards',description:'Edit the three cards displayed immediately below the hero.',fields:[['quick_1_label','First card label','Find us'],['quick_1_title','First card title','Plan your first visit'],['quick_1_url','First card link','#visit'],['quick_2_label','Second card label','Latest message'],['quick_2_title','Second card title','Watch on demand'],['quick_2_url','Second card link','#sermons'],['quick_3_label','Third card label','This week'],['quick_3_title','Third card title','See what’s happening'],['quick_3_url','Third card link','#events']]},
 {title:'About section details',description:'Edit the supporting paragraph, story link and ministry signature.',fields:[['about_secondary_text','Second about paragraph','Whatever your story or season, you are welcome here. Come as you are and discover a place to worship, grow, serve and belong.'],['about_link_text','Story link text','Discover our story →'],['about_link_url','Story link URL','#beliefs'],['signature_text','Ministry signature','Bread of Life DCM']]},
 {title:'Section wording',description:'Titles and introductions for the main homepage sections.',fields:[['leadership_kicker','Pastor section small heading','Our leadership'],['leadership_heading','Pastor section heading','Serving with faith. Leading with love.'],['leadership_text','Pastor section paragraph','Meet the pastors who faithfully teach God’s Word and care for families.'],['community_kicker','Community small heading','Find your community'],['community_heading','Community heading','There’s a place for everyone'],['community_text','Community paragraph','Life is better together. Find connection, purpose and spiritual growth.'],['messages_kicker','Messages small heading','Watch & listen'],['messages_heading','Messages heading','Latest message'],['events_kicker','Events small heading','What’s happening'],['events_heading','Events heading','Upcoming events']]},
 {title:'Family Reached & impact numbers',description:'The four animated statistics and their labels.',fields:[['impact_1_number','First number','250'],['impact_1_label','First label','Families reached'],['impact_2_number','Second number','18'],['impact_2_label','Second label','Outreach projects'],['impact_3_number','Third number','12'],['impact_3_label','Third label','Ministry groups'],['impact_4_number','Fourth number','1'],['impact_4_label','Fourth label','Family in Christ']]},
 {title:'Scripture slideshow',description:'Edit all three Bible verses and references shown between sections.',fields:[['verse_1_text','First verse','“I am the bread of life. Whoever comes to me will never go hungry.”'],['verse_1_ref','First reference','John 6:35'],['verse_2_text','Second verse','“Where the Spirit of the Lord is, there is freedom.”'],['verse_2_ref','Second reference','2 Corinthians 3:17'],['verse_3_text','Third verse','“We walk by faith, not by sight.”'],['verse_3_ref','Third reference','2 Corinthians 5:7']]},
 {title:'“Let Us Know You’re Coming”',description:'First-visit wording, service details and call-to-action.',fields:[['visit_kicker','Small heading','Your first Sunday'],['visit_heading','Visit heading','We can’t wait to meet you.'],['visit_text','Visit paragraph','Visiting a new church can feel like a big step. We’ll make it simple.'],['visit_button','Visit button text','Let us know you’re coming']]},
 {title:'Stories, giving & contact',description:'Testimony, generosity and contact-section wording.',fields:[['stories_kicker','Stories small heading','Stories of grace'],['stories_heading','Stories heading','Lives transformed. Hope restored.'],['stories_text','Stories introduction','God is writing beautiful stories in our community. There is room for your story too.'],['story_quote','Testimony quote','I found more than a church—I found people who prayed with me and helped me grow in faith.'],['story_person','Testimony name','A ministry family'],['giving_kicker','Giving small heading','Generosity'],['giving_heading','Giving heading','We give because God first gave.'],['giving_text','Giving paragraph','Your generosity helps us share the Gospel, care for families and serve our community.'],['giving_button','Giving button text','Give Bountifully'],['contact_kicker','Contact small heading','Connect with us'],['contact_heading','Contact heading','How can we stand with you?'],['contact_text','Contact paragraph','Send a prayer request, ask a question or tell us you’re planning a visit.'],['contact_button','Contact form button','Send message']]},
 {title:'Contact & church information',description:'The directions link opens Google Maps and uses each visitor’s current location as the starting point.',fields:[['church_phone','Church phone','0706 308 3665'],['church_email','Church email','hello@breadoflifedcm.org'],['church_address','Church address','Behind LEA Primary School, Kurudu, Abuja 900109, Federal Capital Territory, Nigeria'],['maps_url','Google Maps directions link','https://www.google.com/maps/dir/?api=1&destination=Bread+of+Life+Divine+Covenant+Ministry%2C+Behind+LEA+Primary+School%2C+Kurudu%2C+Abuja+900109%2C+FCT%2C+Nigeria'],['giving_url','Secure giving link','#contact']]},
 {title:'Footer & navigation wording',description:'Edit public labels without changing the website code.',fields:[['nav_about','About navigation label','About'],['nav_messages','Messages navigation label','Messages'],['nav_connect','Connect navigation label','Connect'],['nav_events','Events navigation label','Events'],['nav_contact','Contact navigation label','Contact'],['footer_tagline','Footer message','Jesus at the centre. People at heart.'],['footer_copyright','Copyright text','© 2026 Bread of Life Divine Covenant Ministry. All rights reserved.']]},
 {title:'Expanded navigation menu',description:'Edit the information visitors see after opening the navigation menu.',fields:[['nav_menu_label','Menu button label','Menu'],['nav_visit_button','Plan-a-visit button','Plan a visit'],['nav_visit_url','Plan-a-visit link','#visit'],['nav_explore_kicker','Connect panel small heading','Find your place'],['nav_explore_heading','Connect panel heading','Life is better in community.'],['nav_explore_text','Connect panel description','Take your next step and grow with people who will walk alongside you.'],['nav_card_1_title','First card title','Ministries'],['nav_card_1_text','First card description','Find your community'],['nav_card_1_url','First card link','#ministries'],['nav_card_2_title','Second card title','Latest messages'],['nav_card_2_text','Second card description','Watch and grow'],['nav_card_2_url','Second card link','#sermons'],['nav_card_3_title','Third card title','Upcoming events'],['nav_card_3_text','Third card description','Gather with us'],['nav_card_3_url','Third card link','#events'],['nav_card_4_title','Fourth card title','Prayer & care'],['nav_card_4_text','Fourth card description','We are here for you'],['nav_card_4_url','Fourth card link','#contact']]},
 {title:'Social media',description:'These links power the icons in the desktop navigation, mobile menu, social rail and footer. Leave a URL empty to hide that platform everywhere.',fields:[['youtube_channel','YouTube channel','https://youtube.com/@bread_of_life_dcm?si=jAxO4XiRqtWS4QZ_'],['instagram_url','Instagram page','https://www.instagram.com/bread_of_life_dcm?stkn=NWRtOXF0dXJnMmVw'],['facebook_url','Facebook page','https://www.facebook.com/profile.php?id=61562933086620'],['tiktok_url','TikTok page','https://vm.tiktok.com/ZS9Smb2A5uNWJ-aSViI/'],['x_url','X / Twitter page',''],['whatsapp_url','WhatsApp link','']]}
] as const;
const impactGroup=groups.find(group=>group.title.startsWith('Family Reached'))!;
const navigationGroups=groups.filter(group=>group.title.toLowerCase().includes('navigation'));
const tabs=[['overview','Overview'],['website','Website editor'],['navigation','Navigation'],['animation','Hero Animation'],['impact','Family Reached'],['hero','Hero slides'],['word','Growing in the Word'],['pastors','Pastors'],['communities','Communities'],['visit','Come As You Are'],['stories','Stories of Grace'],['sermons','YouTube videos'],['events','Events'],['messages','Messages'],['admins','Administrators']] as const;
const collectionConfig:any={
 hero:{section:'hero_slides',title:'Hero slides',description:'Manage the main background images and welcome message.',fields:[{key:'title',label:'Main heading',placeholder:'Encounter God. Discover purpose.'},{key:'subtitle',label:'Small heading',placeholder:'Welcome home'},{key:'description',label:'Tagline',textarea:true},{key:'buttonText',label:'Button text'},{key:'buttonUrl',label:'Button link'}]},
 word:{section:'word_slides',title:'Growing in the Word',description:'Add as many photographs and messages as you need. The slideshow adapts automatically.',fields:[{key:'title',label:'Title'},{key:'subtitle',label:'Small heading'},{key:'description',label:'Description',textarea:true}]},
 pastors:{section:'pastors',title:'Teaching & Pastoral Care',description:'The Head Pastor appears first. Add, reorder, hide or update every pastor here.',fields:[{key:'title',label:'Pastor name'},{key:'subtitle',label:'Ministry title / position',placeholder:'Head Pastor'},{key:'description',label:'Short description',textarea:true},{key:'body',label:'Optional biography',textarea:true},{key:'contactLinks',label:'Optional links',placeholder:'Facebook | https://... (one per line)',textarea:true}]},
 communities:{section:'communities',title:'Find Your Community',description:'All visible groups appear together in a responsive layout.',fields:[{key:'title',label:'Group title'},{key:'subtitle',label:'Short label'},{key:'description',label:'Description',textarea:true},{key:'buttonText',label:'Button text'},{key:'buttonUrl',label:'Button link'}]},
 visit:{section:'visit_slides',title:'Come As You Are',description:'Manage welcome photographs, messages and optional buttons.',fields:[{key:'title',label:'Title'},{key:'subtitle',label:'Small heading'},{key:'description',label:'Message',textarea:true},{key:'buttonText',label:'Button text'},{key:'buttonUrl',label:'Button link'}]},
 stories:{section:'stories',title:'Stories of Grace',description:'Add, edit, reorder, hide or remove testimonies. Photographs are optional.',fields:[{key:'title',label:'Person or family name'},{key:'subtitle',label:'Testimony label',placeholder:'Member testimony'},{key:'description',label:'Story or testimony',textarea:true}]}
};

export default function Dashboard({email}:{email:string}){
 const[data,setData]=useState<Data|null>(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[savedMessage,setSavedMessage]=useState('');
 const load=useCallback(async()=>{const response=await fetch('/api/admin');if(!response.ok)throw new Error('Unable to load the dashboard');setData(await response.json())},[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 const saved=useMemo(()=>Object.fromEntries((data?.settings||[]).map(x=>[x.key,x.value])),[data]);
 async function send(payload:any){setError('');setSavedMessage('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json()).error||'Unable to save');await load();setSavedMessage('Saved');window.setTimeout(()=>setSavedMessage(''),4200)}catch(e:any){setError(e.message);throw e}}
 function submit(action:string,e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;send({action,...Object.fromEntries(new FormData(form))}).then(()=>{if(action==='sermon'||action==='event')form.reset()})}
 function saveGroup(e:FormEvent<HTMLFormElement>){e.preventDefault();send({action:'settings_bulk',values:Object.fromEntries(new FormData(e.currentTarget))})}
 const currentCollection=collectionConfig[tab];
 return <div className="admin-shell"><aside><div className="admin-brand"><img src="/assets/images/bread-of-life-logo.webp" alt="Church logo"/><span><b>Bread of Life</b><small>Content manager</small></span></div><nav>{tabs.map(([key,label])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav><a href="/">← View live website</a><a href="/api/admin-logout">Sign out</a></aside><section className="admin-main"><header><div><small>Secure administration</small><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><span>{email}</span></header>{error&&<p className="admin-alert">{error}</p>}{savedMessage&&<div className="save-toast" role="status" aria-live="polite"><span>✓</span><div><b>Saved successfully</b><small>Your changes are now live on the website.</small></div></div>}{!data?<p>Loading church records…</p>:<>
 {tab==='overview'&&<><div className="stats"><article><b>{data.submissions.length}</b><span>Messages</span></article><article><b>{data.submissions.filter(x=>x.status==='new').length}</b><span>New requests</span></article><article><b>{data.sermons.length}</b><span>YouTube videos</span></article><article><b>{data.events.length}</b><span>Events</span></article></div><div className="panel admin-tip"><h2>Everything in one place</h2><p>Use the menu to edit words, images, pastors, communities, slides, events, videos, social links and service times. Repeatable sections support add, edit, delete, reorder and show/hide.</p></div></>}
 {tab==='messages'&&<div className="panel"><h2>Prayer, visits & enquiries</h2>{!data.submissions.length&&<p>No messages yet.</p>}{data.submissions.map(x=><article className="record" key={x.id}><div><b>{x.name}</b><small>{x.type} · {x.contact}</small><p>{x.message}</p></div><select value={x.status} onChange={e=>send({action:'status',id:x.id,status:e.target.value})}><option>new</option><option>contacted</option><option>resolved</option></select></article>)}</div>}
 {tab==='admins'&&<div className="two"><form className="panel" onSubmit={e=>submit('admin_add',e)}><h2>Add administrator</h2><p>Create a separate login for another trusted administrator.</p><label>Email address<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={10} required/></label><button>Add administrator</button></form><div className="panel"><h2>Administrators</h2>{data.admins.map(x=><article className="record" key={x}><div><b>{x}</b><small>{x===PRIMARY_ADMIN?'Primary administrator':'Administrator'}</small></div>{x!==PRIMARY_ADMIN&&<button type="button" onClick={()=>confirm('Remove this administrator?')&&send({action:'admin_delete',email:x})}>Remove</button>}</article>)}</div></div>}
 {tab==='sermons'&&<Sermons data={data} send={send} submit={submit}/>} {tab==='events'&&<Events data={data} send={send} submit={submit}/>}
 {tab==='website'&&<div className="settings-groups">{groups.filter(g=>g!==impactGroup&&!navigationGroups.includes(g)).map(g=><SettingsGroup key={g.title} group={g} saved={saved} saveGroup={saveGroup}/>)}</div>}
 {tab==='navigation'&&<div className="settings-groups"><div className="panel admin-tip"><h2>Navigation editor</h2><p>Edit the main menu labels, the information shown inside the opened menu, its four feature links, action buttons, and navigation footer.</p></div>{navigationGroups.map(g=><SettingsGroup key={g.title} group={g} saved={saved} saveGroup={saveGroup}/>)}</div>}
 {tab==='animation'&&<HeroAnimation saved={saved} saveGroup={saveGroup}/>}
 {tab==='impact'&&<form className="panel settings-card" onSubmit={saveGroup}><h2>{impactGroup.title}</h2><p>{impactGroup.description}</p><div className="settings-grid">{impactGroup.fields.map(([key,label,fallback])=><label key={key}>{label}<input name={key} type={key.endsWith('_number')?'number':'text'} min={key.endsWith('_number')?'0':undefined} defaultValue={saved[key]||fallback}/></label>)}</div><button>Save Family Reached numbers</button></form>}
 {currentCollection&&<ContentManager {...currentCollection} items={data.contentItems.filter(item=>item.section===currentCollection.section)} send={send}/>}
 </>}</section></div>
}

function SettingsGroup({group,saved,saveGroup}:{group:any;saved:Record<string,string>;saveGroup:(e:FormEvent<HTMLFormElement>)=>void}){
 const isNavigation=group.title.toLowerCase().includes('navigation');
 return <form className="panel settings-card" onSubmit={saveGroup}><h2>{group.title}</h2><p>{group.description}</p><div className="settings-grid">{group.fields.map(([key,label,fallback]:string[])=><label key={key}>{label}{key.includes('_text')||key==='about_text'||key==='hero_tagline'?<textarea name={key} rows={3} defaultValue={saved[key]||fallback}/>:<input name={key} defaultValue={saved[key]||fallback}/>}</label>)}</div><button>{isNavigation?'Save navigation changes':'Save section'}</button></form>
}

function HeroAnimation({saved,saveGroup}:{saved:Record<string,string>;saveGroup:(e:FormEvent<HTMLFormElement>)=>void}){
 const[effect,setEffect]=useState(saved.hero_text_effect||'graceful');
 return <form className="panel settings-card animation-editor" onSubmit={saveGroup}><small>Appearance settings</small><h2>Hero animated text</h2><p>Choose a peaceful, professional motion style for the main welcome text. “Once” is recommended; “Continuous” keeps only a very gentle accent movement after the entrance.</p><div className="animation-preview" data-effect={effect} key={effect}><span>Welcome home</span><b>Encounter God.<em> Discover purpose.</em></b></div><div className="settings-grid"><label>Animation effect<select name="hero_text_effect" value={effect} onChange={e=>setEffect(e.target.value)}><option value="graceful">Graceful reveal — recommended</option><option value="fade">Soft fade upward</option><option value="slide">Gentle side entrance</option><option value="glow">Warm golden glow</option><option value="none">No animation</option></select></label><label>How long each entrance lasts<select name="hero_animation_duration" defaultValue={saved.hero_animation_duration||'1.2'}><option value="0.7">Quick — 0.7 seconds</option><option value="1.2">Balanced — 1.2 seconds</option><option value="1.8">Calm — 1.8 seconds</option><option value="2.5">Slow — 2.5 seconds</option></select></label><label>After the entrance<select name="hero_animation_repeat" defaultValue={saved.hero_animation_repeat||'once'}><option value="once">Play once — recommended</option><option value="continuous">Keep a gentle movement</option></select></label><label>Motion strength<select name="hero_animation_intensity" defaultValue={saved.hero_animation_intensity||'soft'}><option value="soft">Soft — recommended</option><option value="standard">Standard</option></select></label></div><button>Save hero animation</button></form>
}

function Sermons({data,send,submit}:{data:Data;send:(x:any)=>Promise<void>;submit:(a:string,e:FormEvent<HTMLFormElement>)=>void}){return <div className="two"><form className="panel" onSubmit={e=>submit('sermon',e)}><h2>Add YouTube message</h2><label>YouTube link or video ID<input name="youtubeId" required/></label><label>Message title<input name="title" required/></label><label>Pastor or speaker<input name="pastor" required/></label><label>Duration<input name="duration" placeholder="42:10" required/></label><label className="check"><input type="checkbox" name="featured"/> Feature on homepage</label><button>Add message</button></form><div className="panel"><h2>Video library</h2>{data.sermons.map(x=><form className="record-editor" key={x.id} onSubmit={e=>{e.preventDefault();send({action:'edit_sermon',id:x.id,...Object.fromEntries(new FormData(e.currentTarget))})}}><input name="title" defaultValue={x.title}/><input name="youtubeId" defaultValue={x.youtube_id}/><input name="pastor" defaultValue={x.pastor}/><input name="duration" defaultValue={x.duration}/><label className="check"><input type="checkbox" name="featured" defaultChecked={!!x.featured}/> Featured</label><div><button>Save</button><button type="button" className="visibility" onClick={()=>send({action:'toggle_sermon',id:x.id,visible:!x.published})}>{x.published?'Hide':'Show'}</button><button type="button" className="delete" onClick={()=>confirm('Delete this message?')&&send({action:'delete_sermon',id:x.id})}>Delete</button></div></form>)}</div></div>}
function Events({data,send,submit}:{data:Data;send:(x:any)=>Promise<void>;submit:(a:string,e:FormEvent<HTMLFormElement>)=>void}){
 const[notice,setNotice]=useState('');
 async function upload(file:File,target:HTMLInputElement){setNotice('Uploading image…');const form=new FormData();form.append('image',file);const response=await fetch('/api/admin/upload',{method:'POST',body:form});if(!response.ok){setNotice('Image upload failed.');return}target.value=(await response.json()).url;setNotice('Image uploaded. Click Save to publish it.')}
 const imageFields=(value='')=><><label>Event image URL (optional)<input name="imageUrl" defaultValue={value} placeholder="Upload an image or paste a URL"/></label><label className="upload-button">Upload event image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0],target=e.currentTarget.closest('form')?.querySelector<HTMLInputElement>('input[name="imageUrl"]');if(file&&target)upload(file,target)}}/></label></>;
 return <div className="two"><form className="panel event-editor" onSubmit={e=>submit('event',e)}><h2>Add upcoming event</h2><label>Event name<input name="title" required/></label><label>Date<input name="eventDate" type="date" required/></label><label>Time<input name="eventTime" type="time" required/></label><label>Location<input name="location"/></label><label>Event information<textarea name="description" rows={4} placeholder="What should visitors know about this event?"/></label>{imageFields()}<button>Add event</button>{notice&&<p className="admin-notice">{notice}</p>}</form><div className="panel"><h2>Upcoming events</h2>{!data.events.length&&<p>No events yet.</p>}{data.events.map(x=><form className="record-editor event-record-editor" key={x.id} onSubmit={e=>{e.preventDefault();send({action:'edit_event',id:x.id,...Object.fromEntries(new FormData(e.currentTarget))})}}><input name="title" defaultValue={x.title}/><input name="eventDate" type="date" defaultValue={x.event_date}/><input name="eventTime" type="time" defaultValue={x.event_time}/><input name="location" defaultValue={x.location}/><textarea name="description" rows={3} defaultValue={x.description} placeholder="Event information"/>{imageFields(x.image_url)}<div><button>Save</button><button type="button" className="visibility" onClick={()=>send({action:'toggle_event',id:x.id,visible:!x.published})}>{x.published?'Hide':'Show'}</button><button type="button" className="delete" onClick={()=>confirm('Delete this event?')&&send({action:'delete_event',id:x.id})}>Delete</button></div></form>)}</div></div>
}
