import Image from'next/image';import{env}from'cloudflare:workers';import ContactForm from'./contact-form';
export const dynamic='force-dynamic';const fallback=[{title:'Sunday Worship',event_date:'Sunday',event_time:'8:00 AM & 10:30 AM'},{title:'Word & Prayer',event_date:'Wednesday',event_time:'5:30 PM'},{title:'Covenant Prayer',event_date:'Friday',event_time:'6:00 PM'}];
export default async function Home(){let settings:Record<string,string>={};let sermons:any[]=[];let events:any[]=fallback;try{const[s,v,e]=await Promise.all([env.DB.prepare('SELECT key,value FROM settings').all(),env.DB.prepare('SELECT * FROM sermons WHERE published=1 ORDER BY featured DESC,id DESC LIMIT 6').all(),env.DB.prepare("SELECT * FROM events WHERE published=1 AND event_date>=date('now') ORDER BY event_date LIMIT 6").all()]);settings=Object.fromEntries((s.results as any[]).map(x=>[x.key,x.value]));sermons=v.results;if(e.results.length)events=e.results}catch{}
const channel=settings.youtube_channel||'https://youtube.com/@bread_of_life_dcm';return <main>
<div className="announcement">Join us this Sunday · 8:00 AM & 10:30 AM <a href="#visit">Plan your visit →</a></div>
<header><a className="brand" href="#top"><Image src="/logo.png" width={58} height={58} alt="Bread of Life Divine Covenant Ministry"/><span><b>Bread of Life</b><small>Divine Covenant Ministry</small></span></a><nav><a href="#about">About</a><a href="#sermons">Messages</a><a href="#events">Events</a><a href="#contact">Contact</a><a className="admin-link" href="/admin">Admin</a></nav></header>
<section className="hero" id="top"><div className="shade"/><div className="hero-copy"><p className="eyebrow">— Welcome home</p><h1>Encounter God.<br/><em>Discover purpose.</em></h1><p>{settings.hero_tagline||'A place to belong. A people becoming like Christ.'}</p><div className="actions"><a className="primary" href="#visit">Plan your visit</a><a className="ghost" href="#sermons">▶ Watch a message</a></div></div><div className="emblem"><Image src="/logo.png" width={520} height={520} alt="" priority/></div></section>
<section className="intro" id="about"><p className="kicker">Who we are</p><div><h2>More than a service.<br/><em>A family to call home.</em></h2><p>We are a growing family of believers committed to knowing Jesus, living His Word and sharing His love with our community. Whatever your story or season, you are welcome here.</p></div></section>
<section className="sermons" id="sermons"><p className="kicker">Watch & listen</p><h2>Messages that build faith</h2><p>Watch worship services, teachings and ministry moments from Bread of Life Divine Covenant Ministry.</p><a className="primary" href={channel} target="_blank">Visit our YouTube channel ↗</a><div className="video-list">{sermons.length?sermons.map(x=><article className="video-placeholder" key={x.id}><iframe src={'https://www.youtube.com/embed/'+x.youtube_id} title={x.title} allowFullScreen/><h3>{x.title}</h3><p>{x.pastor} · {x.duration}</p></article>):<div className="video-placeholder"><span>▶</span><h3>Videos managed from your dashboard</h3><p>Add a YouTube link, pastor, title and duration in Admin.</p></div>}</div></section>
<section className="events" id="events"><p className="kicker">What’s happening</p><h2>Upcoming events</h2><div className="event-grid">{events.map((x,i)=><article key={x.id||i}><b>{x.title}</b><span>{x.event_date} · {x.event_time}</span></article>)}</div></section>
<section className="visit" id="visit"><div><p className="kicker">Your first Sunday</p><h2>We can’t wait<br/>to meet you.</h2><p>Visiting a new church can feel like a big step. We’ll make it simple and welcoming.</p></div><ContactForm/></section>
<footer id="contact"><Image src="/logo.png" width={64} height={64} alt=""/><div><b>Bread of Life Divine Covenant Ministry</b><small>Jesus at the centre. People at heart.</small></div><a href="/admin">Church administration</a></footer></main>}
